### ISSUE TITLE
Tublin fluorescence fluctuation data set simulation

### ISSUE THREAD

**Issue by yrl1120** [DominiqueBourgeois/SMIS#1]
I am trying to learn to use this software for the purpose of simulating a microtubule dataset of fluorescence fluctuations for reconstruction, but I have just started to get in touch with simulated data and I am not sure if this software can achieve this function? I would be grateful if you could let me know.
Like this one：[test_input.zip](https://github.com/DominiqueBourgeois/SMIS/files/12547268/test_input.zip)

**Comment by DominiqueBourgeois** [comment]
Hi, 
Most probably yes, you could simulate data that look very much like your test_input.tif (this is an experimental data set similar to SOFI right ?). The point is to use the right fluorophore (with suitable blinking) and a proper imaging scheme.

**Comment by yrl1120** [comment]
Hi, that would be nice to be able to simulate a set of SOFI data, could you suggest me a suitable fluorescence and imaging scheme, I'd be appreciate if you could help me.

**Comment by yrl1120** [comment]
Sorry to bother you again, I have a problem with the «Setup Fluorophore »part, it seems that matlab does not run properly in this part of the code, and it does not close properly after opening, and this problem also seems to affect the following simulation.**
![image](https://github.com/DominiqueBourgeois/SMIS/assets/118066608/57c2c99d-70cd-41b9-8bd9-25d5e12a1290)
**

**Comment by DominiqueBourgeois** [comment]
What version of SMIS are you using, and which operating system ? 
Can you tell me the sequence of commands that you have used to arrive at this bug ?
What error message do you get on the message window ?

**Comment by DominiqueBourgeois** [comment]
Setting up a SOFI experiment is actually very easy: just use EGFP with a 488 laser. EGFP molecules will flicker and bleach progressively. I can send you the .mat SMIS file directly by email if you want !

**Comment by yrl1120** [comment]
Thanks a lot. My email is: yanru.li@stfc.ac.uk. The version is SMIS 2.2, I think the problem is when I click the «Setup Fluorophore », I can't close this window by clicking Cancle or OK, and some information is different from the manual.
