### ISSUE TITLE
How to set the signal-to-noise ratio of simulated data?

### ISSUE THREAD

**Issue by RecardoLyu** [DominiqueBourgeois/SMIS#2]
Hi,
I'm learning how to use this software to generate a saries SMLM data that have different SNR. But I couldn't work it out. I'm not sure whether this function is implemented or not? I would be grateful if you'd let me know.

**Comment by DominiqueBourgeois** [comment]
Dear Recardo, 

There are several ways you can change the SNR in SMIS simulated data sets: 
=> you can change the fluorescence background level 
=> you can change laser intensities 
=> you can change frametime 
=> you can change pixel size 
=> you can change numerical aperture of the objective 
=> you can change EMCCD setup (EMCCD gain). 
=> you can change the fluorescence quantum yield of your fluorophore (although this is not representative of real life) 

Basically you have to imagine that you are working with a real microscope. 

All the best, 
Dominique 


De: "RecardoLyu" ***@***.***> 
À: "DominiqueBourgeois/SMIS" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Jeudi 18 Janvier 2024 07:42:39 
Objet: [DominiqueBourgeois/SMIS] How to set the signal-to-noise ratio of simulated data? (Issue #2) 





Hi, 
I'm learning how to use this software to generate a saries SMLM data that have different SNR. But I couldn't work it out. I'm not sure whether this function is implemented or not? I would be grateful if you'd let me know.
